name: Simple action
author: Serve Laurijssen

inputs:
  who_to_greet: 
    description: "who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "time of greeting"
    
runs:
  using: "node16"
  main:
    index.js
